version: '3.6'
services:
  api:
    build: .
    working_dir: /app
    command: yarn run start
    volumes:
      - .:/app
    ports:
      - 4002:4002
    depends_on:
      - postgres
    env_file: .env
  postgres:
    image: postgres:11.4-alpine
    ports:
      - 5444:5444
    env_file: .env
