version: '3'
services:
  api:
    build: .
    working_dir: /app
    command: yarn run start:dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file: .env
  postgres:
    image: postgres:11.4-alpine
    ports:
      - 5432:5432
    env_file: .env
